### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/WildChests#177]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-61 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 47c34ca on HEAD)
You are running 11 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Purpur-1933 (MC: 1.19.3)

### Plugin's Version

#5 27/05/2023 18:11:00

### Describe the bug

https://pastebin.com/1npJACyF

### To Reproduce

https://pastebin.com/1npJACyF

**Comment by OmerBenGera** [comment]
Contact Drop2InventoryPlus regarding this, this has nothing to do with WildChests.

**Comment by mfnalex** [comment]
> Contact Drop2InventoryPlus regarding this, this has nothing to do with WildChests.

No, this is an issue on your side. According to the API docs, WildChestsAPI#getStorageChest must return null if it's not a storage chest, instead of failing into a ClassCastException -> https://bg-software.com/wildchests/api/com/bgsoftware/wildchests/api/WildChestsAPI.html#getStorageChest-org.bukkit.Location-
