### ISSUE TITLE
Auto Sell Chests not selling

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/WildChests#192]
### Minecraft's Version

Current: git-Purpur-2004 (MC: 1.20.1)*

### Plugin's Version

WildChests-2023.2-b12

### Describe the bug

Latest dev version doesn't sell items

### To Reproduce

Get the latest dev version, place down auto seller, put stuff in

**Comment by OmerBenGera** [comment]
Seems to work just fine for me.
What prices provider do you use?

**Comment by DuneSciFye** [comment]
I used WildChests

**Comment by OmerBenGera** [comment]
Works just fine for me.

**Comment by Doggi-Youngster** [comment]
> Works just fine for me. Upload your config file to pastebin and send it here

I have the same problem, I don't think it has to do with the config, items like COOKED_BEEF, ROTTEN_FLESH, SCULK_CATALYST, and other items don't work. Here's my config:
`#########################################################
##                                                     ##
##              WildChests Configuration               ##
##                 Developed by Ome_R                  ##
##                                                     ##
#########################################################

# How much time should be passed between sell and crafting notifies? (in ticks)
# Set 0 to disable this feature.
notifier-interval: 1200

# When enabled there will be a list of items that has been sold and crafted.
detailed-notifier: true

# When enabled, a gui will be popped to confirm chest expand purchase. Otherwise, it will be done in chat.
confirm-gui: true

# Specify a command to be executed when a sell is running.
# {player-name} - use as the player's name
# {price} - use as the price of item
# Set to '' in order to disable the feature.
sell-command: ''

# When enabled, the values will be formatted (e.g 10B, 1T)
sell-format: false

# Should the chest item be dropped on explosions?
# Set a chance of it to get dropped between 0 and 100.
explode-drop-chance: 100

# Choose which prices plugin to check for prices (Auto, CMI, EconomyShopGUI, Essentials, GUIShop, newtShop, QuantumShop, ShopGUIPlus, zShop).
prices-provider: 'Essentials'

# What stacker provider should the plugin use? (WildStacker, RoseStacker, Auto)
stacker-provider: 'Auto'

# Built-in prices list.
# Use the "ID:PRICE" or "ID:DATA:PRICE" formats.
prices-list:
- 'COAL:30'
- 'COPPER_INGOT:60'
- 'IRON_INGOT:90'
- 'GOLD_INGOT:150'
- 'DIAMOND:300'
- 'AMETHYST:325'
- 'EMERALD:400'
- 'NETHERITE_SCRAP:750'
- 'NETHER_STAR:175000'
- 'ROTTEN_FLESH:3'
- 'BONE:7'
- 'STRING:9'
- 'SPIDER_EYE:10'
- 'GUNPOWDER:15'
- 'LEATHER:23'
- 'ENDER_PEARL:75'
- 'SLIME_BALL:125'
- 'GLOW_INK_SACK:175'
- 'BLAZE_POWDER:250'
- 'SCULK_CATALYST:1250000'
- 'CARROT:7'
- 'WHEAT:10'
- 'APPLE:25'
- 'CACTUS:30'
- 'SUGAR_CANE:37'
- 'PUMPKIN:40'
- 'WATERMELON:40'
- 'SWEET_BERRIES:10'
- 'COOKED_BEEF:5'

# All settings related to database.
database:
  # Automatically delete data from invalid worlds.
  invalid-world-delete: false

# All settings related to hooks
hooks:
  # Should items dropped by the plugin get directly stacked by WildStacker?
  wildstacker: true

# The maximum pickup delay items can have for the suction chests to pick them up.
maximum-pickup-delay: 32767

# The plugin brings tons of new custom and unique chests to your server. All the chests are configurable, and
# you can create and mix between them. You can create chests that stores infinite amount of items, chests that
# are connected to player vaults or factions, linked chests and many more!
#
# *** Chest Mode ***
# Chests in this mode react like regular chests. This is the base mode, and used for creating
# sell chests and larger chests.
#
# *** Linked Mode ***
# Chests in this mode are all linked together, and work like ender chests, but globally.
#
# *** Storage Units Mode ***
# Chests in this mode will have unlimited amount of storage, but only for one specific item.
# Note: Auto sell & auto craft modes doesn't work for this mode!
#
# There are sections that can be applied to all of the chests:
# size: Amount of rows the chest will have (INTEGER) (Will be overridden by pages' size)
# title: Global title for all pages. Will be overridden by page's title (STRING)
# sell-chest: Should items in this chest will be sold to the chest placer? (BOOLEAN)
# crafter-chest: List of recipes that will take action in this chest (LIST)
#      Please follow "TYPE" and "TYPE:DATA" formats
# hopper-filter: When enabled, only craftable items will go into hoppers below (BOOLEAN)
# pages: Section that handles all settings for pages
# pages.default: Default amount of pages (INTEGER) [REQUIRED FOR PAGES]
# pages.<#>: Section that handles all settings for a specific page
# pages.<#>.price: Price for upgrading to that page (DOUBLE) [REQUIRED]
# pages.<#>.title: Custom title for that page.
# item.name: Custom name for the chest (STRING)
# item.lore: Custom lore for the chest (LIST)
# multiplier: Money multiplier for sell chests. (DOUBLE)
# deposit-method: Transfer the money received by the sell chest to a skyblock/faction bank
#     Currently supported: Vault, SuperiorSkyblock2
# auto-collect: Should items get directly into inventory after breaking? (BOOLEAN)
# auto-suction.range: Should items inside the specified range will get suctioned into the chest? (INTEGER)
# auto-suction.chunk: Should items inside the chunk will get suctioned into the chest? (BOOLEAN)
#      If you set it to true, the range will be checked as y-range only.
# blacklist: A list of items that won't be picked up by the chests (only works for auto-suction for now)
# whitelist: A list of items that will be picked up by the chests (only works for auto-suction for now)
# particles: A list of particles that will be shown to the chest.

chests:
  linked_chest:
    chest-mode: LINKED_CHEST
    title: Linked Chest
    item:
      name: '&6Linked Chest &7(Place to active)'
    particles:
      - CRIT
  large_chest:
    chest-mode: CHEST
    size: 6
    item:
      name: '&aLarge Chest &7(Place to active)'
    pages:
      default: 1
      '2':
        price: 500000.0
        title: 'Chest #2'
      '3':
        price: 1000000.0
        title: 'Chest #3'
      '4':
        price: 2000000.0
        title: 'Chest #4'
      '5':
        price: 3000000.0
        title: 'Chest #5'
    particles:
      - TOTEM
  sell_chest:
    chest-mode: CHEST
    size: 6
    title: Drop your items here to sell them.
    item:
      name: '&dSell Chest &7(Place to active)'
    sell-mode: true
    particles:
      - SPELL_WITCH
  auto_crafter:
    chest-mode: CHEST
    size: 6
    title: Drop your items here to auto-craft them.
    item:
      name: '&cAuto Crafter &7(Place to active)'
    crafter-chest:
      - GOLD_INGOT
    particles:
      - LANDING_LAVA
  storage_unit:
    chest-mode: STORAGE_UNIT
    size: 3
    title: Storage Unit {0}
    item:
      name: '&bStorage Unit &7(Place to active)'
    particles:
      - CRIT_MAGIC
  chunk_collector:
    chest-mode: CHEST
    size: 6
    title: Chunk Collector
    item:
      name: '&eChunk Collector &7(Place to active)'
    auto-suction:
      range: 5
      chunk: true
    particles:
      - SMOKE_NORMAL
      - FLAME`

**Comment by DuneSciFye** [comment]
Oops, forgot about this, shall I upload mine again?

**Comment by OmerBenGera** [comment]
> Oops, forgot about this, shall I upload mine as well?

Yes please.

**Comment by OmerBenGera** [comment]
> > Works just fine for me. Upload your config file to pastebin and send it here
> 
> I have the same problem, I don't think it has to do with the config, items like COOKED_BEEF, ROTTEN_FLESH, SCULK_CATALYST, and other items don't work. Here's my config:
> 
> ```
> ##                                                     ##
> ##              WildChests Configuration               ##
> ##                 Developed by Ome_R                  ##
> ##                                                     ##
> #########################################################
> 
> # How much time should be passed between sell and crafting notifies? (in ticks)
> # Set 0 to disable this feature.
> notifier-interval: 1200
> 
> # When enabled there will be a list of items that has been sold and crafted.
> detailed-notifier: true
> 
> # When enabled, a gui will be popped to confirm chest expand purchase. Otherwise, it will be done in chat.
> confirm-gui: true
> 
> # Specify a command to be executed when a sell is running.
> # {player-name} - use as the player's name
> # {price} - use as the price of item
> # Set to '' in order to disable the feature.
> sell-command: ''
> 
> # When enabled, the values will be formatted (e.g 10B, 1T)
> sell-format: false
> 
> # Should the chest item be dropped on explosions?
> # Set a chance of it to get dropped between 0 and 100.
> explode-drop-chance: 100
> 
> # Choose which prices plugin to check for prices (Auto, CMI, EconomyShopGUI, Essentials, GUIShop, newtShop, QuantumShop, ShopGUIPlus, zShop).
> prices-provider: 'Essentials'
> 
> # What stacker provider should the plugin use? (WildStacker, RoseStacker, Auto)
> stacker-provider: 'Auto'
> 
> # Built-in prices list.
> # Use the "ID:PRICE" or "ID:DATA:PRICE" formats.
> prices-list:
> - 'COAL:30'
> - 'COPPER_INGOT:60'
> - 'IRON_INGOT:90'
> - 'GOLD_INGOT:150'
> - 'DIAMOND:300'
> - 'AMETHYST:325'
> - 'EMERALD:400'
> - 'NETHERITE_SCRAP:750'
> - 'NETHER_STAR:175000'
> - 'ROTTEN_FLESH:3'
> - 'BONE:7'
> - 'STRING:9'
> - 'SPIDER_EYE:10'
> - 'GUNPOWDER:15'
> - 'LEATHER:23'
> - 'ENDER_PEARL:75'
> - 'SLIME_BALL:125'
> - 'GLOW_INK_SACK:175'
> - 'BLAZE_POWDER:250'
> - 'SCULK_CATALYST:1250000'
> - 'CARROT:7'
> - 'WHEAT:10'
> - 'APPLE:25'
> - 'CACTUS:30'
> - 'SUGAR_CANE:37'
> - 'PUMPKIN:40'
> - 'WATERMELON:40'
> - 'SWEET_BERRIES:10'
> - 'COOKED_BEEF:5'
> 
> # All settings related to database.
> database:
>   # Automatically delete data from invalid worlds.
>   invalid-world-delete: false
> 
> # All settings related to hooks
> hooks:
>   # Should items dropped by the plugin get directly stacked by WildStacker?
>   wildstacker: true
> 
> # The maximum pickup delay items can have for the suction chests to pick them up.
> maximum-pickup-delay: 32767
> 
> # The plugin brings tons of new custom and unique chests to your server. All the chests are configurable, and
> # you can create and mix between them. You can create chests that stores infinite amount of items, chests that
> # are connected to player vaults or factions, linked chests and many more!
> #
> # *** Chest Mode ***
> # Chests in this mode react like regular chests. This is the base mode, and used for creating
> # sell chests and larger chests.
> #
> # *** Linked Mode ***
> # Chests in this mode are all linked together, and work like ender chests, but globally.
> #
> # *** Storage Units Mode ***
> # Chests in this mode will have unlimited amount of storage, but only for one specific item.
> # Note: Auto sell & auto craft modes doesn't work for this mode!
> #
> # There are sections that can be applied to all of the chests:
> # size: Amount of rows the chest will have (INTEGER) (Will be overridden by pages' size)
> # title: Global title for all pages. Will be overridden by page's title (STRING)
> # sell-chest: Should items in this chest will be sold to the chest placer? (BOOLEAN)
> # crafter-chest: List of recipes that will take action in this chest (LIST)
> #      Please follow "TYPE" and "TYPE:DATA" formats
> # hopper-filter: When enabled, only craftable items will go into hoppers below (BOOLEAN)
> # pages: Section that handles all settings for pages
> # pages.default: Default amount of pages (INTEGER) [REQUIRED FOR PAGES]
> # pages.<#>: Section that handles all settings for a specific page
> # pages.<#>.price: Price for upgrading to that page (DOUBLE) [REQUIRED]
> # pages.<#>.title: Custom title for that page.
> # item.name: Custom name for the chest (STRING)
> # item.lore: Custom lore for the chest (LIST)
> # multiplier: Money multiplier for sell chests. (DOUBLE)
> # deposit-method: Transfer the money received by the sell chest to a skyblock/faction bank
> #     Currently supported: Vault, SuperiorSkyblock2
> # auto-collect: Should items get directly into inventory after breaking? (BOOLEAN)
> # auto-suction.range: Should items inside the specified range will get suctioned into the chest? (INTEGER)
> # auto-suction.chunk: Should items inside the chunk will get suctioned into the chest? (BOOLEAN)
> #      If you set it to true, the range will be checked as y-range only.
> # blacklist: A list of items that won't be picked up by the chests (only works for auto-suction for now)
> # whitelist: A list of items that will be picked up by the chests (only works for auto-suction for now)
> # particles: A list of particles that will be shown to the chest.
> 
> chests:
>   linked_chest:
>     chest-mode: LINKED_CHEST
>     title: Linked Chest
>     item:
>       name: '&6Linked Chest &7(Place to active)'
>     particles:
>       - CRIT
>   large_chest:
>     chest-mode: CHEST
>     size: 6
>     item:
>       name: '&aLarge Chest &7(Place to active)'
>     pages:
>       default: 1
>       '2':
>         price: 500000.0
>         title: 'Chest #2'
>       '3':
>         price: 1000000.0
>         title: 'Chest #3'
>       '4':
>         price: 2000000.0
>         title: 'Chest #4'
>       '5':
>         price: 3000000.0
>         title: 'Chest #5'
>     particles:
>       - TOTEM
>   sell_chest:
>     chest-mode: CHEST
>     size: 6
>     title: Drop your items here to sell them.
>     item:
>       name: '&dSell Chest &7(Place to active)'
>     sell-mode: true
>     particles:
>       - SPELL_WITCH
>   auto_crafter:
>     chest-mode: CHEST
>     size: 6
>     title: Drop your items here to auto-craft them.
>     item:
>       name: '&cAuto Crafter &7(Place to active)'
>     crafter-chest:
>       - GOLD_INGOT
>     particles:
>       - LANDING_LAVA
>   storage_unit:
>     chest-mode: STORAGE_UNIT
>     size: 3
>     title: Storage Unit {0}
>     item:
>       name: '&bStorage Unit &7(Place to active)'
>     particles:
>       - CRIT_MAGIC
>   chunk_collector:
>     chest-mode: CHEST
>     size: 6
>     title: Chunk Collector
>     item:
>       name: '&eChunk Collector &7(Place to active)'
>     auto-suction:
>       range: 5
>       chunk: true
>     particles:
>       - SMOKE_NORMAL
>       - FLAME```
> ```

You configured your prices provider to be Essentials - have you set prices for these items in Essentials's config?

**Comment by Doggi-Youngster** [comment]
> > > Works just fine for me. Upload your config file to pastebin and send it here
> > 
> > 
> > I have the same problem, I don't think it has to do with the config, items like COOKED_BEEF, ROTTEN_FLESH, SCULK_CATALYST, and other items don't work. Here's my config:
> > ```
> > ...
> > ```
> 
> You configured your prices provider to be Essentials - have you set prices for these items in Essentials's config?

Could that be it? I don't think I had to do this with the other items.

**Comment by OmerBenGera** [comment]
You should configure your prices provider to the correct one.
If you want the prices to be taken from WC's config file, use "WildChests".

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
