### ISSUE TITLE
Linking a chest caused a stack overflow error and crashed the server

### ISSUE THREAD

**Issue by dro1d-89o** [BG-Software-LLC/WildChests#82]
### Minecraft's Version

1.18.1 Paper.jar

### Plugin's Version

2.2.3

### Describe the bug

[03:51:06] [Server thread/WARN]: Nag author(s): '[Ome_R]' of 'WildChests' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).

Stack overflow error?

### To Reproduce

Link 4 chests together?

### Additional Information

was using linked chests to set up a storage sorting system, accidentally linked 4 chests together instead of 2 like I wanted to.

[Gist - Server Log](https://gist.github.com/dro1d-89o/b22c748434159118e438695ee4451f12)

**Comment by OmerBenGera** [comment]
Let me know how to replicate the issue.

**Comment by dro1d-89o** [comment]
I'm not too sure why it happened, however it happend right after I linked the 4th chest together (4 chests all liked to the same inventory)

**Comment by OmerBenGera** [comment]
Try replicating it again, then tell me exactly how you linked the chests.

**Comment by dro1d-89o** [comment]
as I am currently out of the house, I will do it when I get home later tonight and update you on this.

**Comment by OmerBenGera** [comment]
> as I am currently out of the house, I will do it when I get home later tonight and update you on this.

No worries.

**Comment by dro1d-89o** [comment]
Good morning, I've recorded it happening and have uploaded it as unlisted on YouTube. the link can be found below. I hope this helps.
[Video of it happening](https://youtu.be/Mqtq8poRXIU)

**Comment by OmerBenGera** [comment]
Are you able to narrow it down to a fewer chests and that many?
I can't track what you're doing there and I can't find what causes it like that.

**Comment by dro1d-89o** [comment]
what i did in the video is basically this, lets say you have 8 chests and they all need to link together. the easiest way to do that is to link one chest to all the others (see image below) and then repeat that for all 8 chests you want to link.

I have a feeling that this may have something to do with all the hoppers trying to take out the same item from the inventory because it only happens when there are items going through the system.
![image](https://user-images.githubusercontent.com/62203146/147798067-23fdee2b-605c-4e34-82eb-f8f2d0845484.png)

**Comment by McBesser** [comment]
I don't know whether the topic is still up-to-date or whether that helps, since I currently still have the same version on it and link boxes with a similar scheme as shown above are linked, there is such an output in the console. I can't see any restriction, the boxes are all linked.

`[Mo., 10. Jan. 2022 18:39:19 INFO] Couldn't load the location oneblock_world, 306, 2, -142
[Mo., 10. Jan. 2022 18:39:19 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:19 INFO] Couldn't load the location oneblock_world, 603, 45, 147
[Mo., 10. Jan. 2022 18:39:19 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:19 INFO] Couldn't load the location oneblock_world, 474, 28, 273
[Mo., 10. Jan. 2022 18:39:19 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:19 INFO] Couldn't load the location oneblock_world_nether, 135, 2, 224
[Mo., 10. Jan. 2022 18:39:19 INFO] Index 0 out of bounds for length 0
[18:39]
[Mo., 10. Jan. 2022 18:39:19 INFO] Couldn't load the location oneblock_world_nether, 115, 2, 224
[Mo., 10. Jan. 2022 18:39:21 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:21 INFO] Couldn't load the location oneblock_world_nether, 95, 2, 224
[Mo., 10. Jan. 2022 18:39:21 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:21 INFO] Couldn't load the location oneblock_world_nether, 135, 2, 204
[Mo., 10. Jan. 2022 18:39:21 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:21 INFO] Couldn't load the location oneblock_world_nether, 115, 2, 204
[Mo., 10. Jan. 2022 18:39:21 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:21 INFO] Couldn't load the location oneblock_world_nether, 95, 2, 204
[Mo., 10. Jan. 2022 18:39:21 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:21 INFO] Couldn't load the location oneblock_world_nether, 135, 2, 184
[Mo., 10. Jan. 2022 18:39:21 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:21 INFO] Couldn't load the location oneblock_world_nether, 115, 2, 184
[Mo., 10. Jan. 2022 18:39:21 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:21 INFO] Couldn't load the location oneblock_world_nether, 95, 2, 184
[Mo., 10. Jan. 2022 18:39:21 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:21 INFO] Couldn't load the location oneblock_world_nether, 184, 22, 224
[Mo., 10. Jan. 2022 18:39:21 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:21 INFO] Couldn't load the location oneblock_world_nether, 204, 22, 224
[Mo., 10. Jan. 2022 18:39:21 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:21 INFO] Couldn't load the location oneblock_world_nether, 224, 22, 224
[Mo., 10. Jan. 2022 18:39:21 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:21 INFO] Couldn't load the location oneblock_world, 450, 28, 273
[18:39]
[Mo., 10. Jan. 2022 18:39:21 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:23 INFO] Couldn't load the location oneblock_world, 458, 28, 273
[Mo., 10. Jan. 2022 18:39:23 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:23 INFO] Couldn't load the location oneblock_world, 466, 28, 273
[Mo., 10. Jan. 2022 18:39:23 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:23 INFO] Couldn't load the location oneblock_world, 474, 28, 254
[Mo., 10. Jan. 2022 18:39:23 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:23 INFO] Couldn't load the location oneblock_world, 450, 28, 254
[Mo., 10. Jan. 2022 18:39:23 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:23 INFO] Couldn't load the location oneblock_world, 466, 28, 254
[Mo., 10. Jan. 2022 18:39:23 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:23 INFO] Couldn't load the location oneblock_world, 458, 28, 254
[Mo., 10. Jan. 2022 18:39:23 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:23 INFO] Couldn't load the location oneblock_world, 510, 28, 272
[Mo., 10. Jan. 2022 18:39:23 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:23 INFO] Couldn't load the location oneblock_world, 502, 28, 272
[Mo., 10. Jan. 2022 18:39:23 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:23 INFO] Couldn't load the location oneblock_world, 486, 28, 272
[Mo., 10. Jan. 2022 18:39:23 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:23 INFO] Couldn't load the location oneblock_world, 494, 28, 272
[Mo., 10. Jan. 2022 18:39:23 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:23 INFO] Couldn't load the location oneblock_world, 510, 28, 254
[Mo., 10. Jan. 2022 18:39:23 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:23 INFO] Couldn't load the location oneblock_world, 502, 28, 254
[18:39]
[Mo., 10. Jan. 2022 18:39:23 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:25 INFO] Couldn't load the location oneblock_world, 494, 28, 254
[Mo., 10. Jan. 2022 18:39:25 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:25 INFO] Couldn't load the location oneblock_world, 486, 28, 254
[Mo., 10. Jan. 2022 18:39:25 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:25 INFO] Couldn't load the location oneblock_world_nether, 173, 15, 179
[Mo., 10. Jan. 2022 18:39:25 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:25 INFO] Couldn't load the location oneblock_world_nether, 184, 22, 184
[Mo., 10. Jan. 2022 18:39:25 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:25 INFO] Couldn't load the location oneblock_world_nether, 204, 22, 184
[Mo., 10. Jan. 2022 18:39:25 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:25 INFO] Couldn't load the location oneblock_world_nether, 224, 22, 184
[Mo., 10. Jan. 2022 18:39:25 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:25 INFO] Couldn't load the location oneblock_world_nether, 184, 22, 204
[Mo., 10. Jan. 2022 18:39:25 INFO] [Simple Elevators] A new update is available at:
[Mo., 10. Jan. 2022 18:39:25 INFO] https://www.spigotmc.org/resources/44462/updates
[Mo., 10. Jan. 2022 18:39:25 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:25 INFO] Couldn't load the location oneblock_world_nether, 204, 22, 204
[Mo., 10. Jan. 2022 18:39:25 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:25 INFO] Couldn't load the location oneblock_world_nether, 224, 22, 204
[Mo., 10. Jan. 2022 18:39:25 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:25 INFO] Couldn't load the location oneblock_world_nether, 115, 26, 116
[Mo., 10. Jan. 2022 18:39:25 INFO] Index 0 out of bounds for length 0
SpigotMC - High Performance Minecraft
Simple Elevators | [1.8 - 1.18]

[18:39]
[Mo., 10. Jan. 2022 18:39:25 INFO] Couldn't load the location oneblock_world_nether, 172, 12, 183
[Mo., 10. Jan. 2022 18:39:27 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:27 INFO] Couldn't load the location oneblock_world_nether, 172, 12, 186
[Mo., 10. Jan. 2022 18:39:27 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:27 INFO] Couldn't load the location oneblock_world, 25, 31, 156
[Mo., 10. Jan. 2022 18:39:27 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:27 INFO] Couldn't load the location oneblock_world, 624, 44, 136
[Mo., 10. Jan. 2022 18:39:27 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:27 INFO] Couldn't load the location oneblock_world, 553, 4, 330
[Mo., 10. Jan. 2022 18:39:27 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:27 INFO] Couldn't load the location oneblock_world, 406, 4, 329
[Mo., 10. Jan. 2022 18:39:27 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:27 INFO] Couldn't load the location oneblock_world, 420, 28, 254
[Mo., 10. Jan. 2022 18:39:27 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:27 INFO] Couldn't load the location oneblock_world, 481, 28, 322
[Mo., 10. Jan. 2022 18:39:27 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:27 INFO] Couldn't load the location oneblock_world, 500, 28, 315
[Mo., 10. Jan. 2022 18:39:27 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:27 INFO] Couldn't load the location oneblock_world, 500, 28, 296
[Mo., 10. Jan. 2022 18:39:27 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:27 INFO] Couldn't load the location oneblock_world, 500, 28, 334
[Mo., 10. Jan. 2022 18:39:27 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:27 INFO] Couldn't load the location oneblock_world, -32, 37, -478
[Mo., 10. Jan. 2022 18:39:27 INFO] Index 0 out of bounds for length 0
[18:39]
[Mo., 10. Jan. 2022 18:39:27 INFO] Couldn't load the location oneblock_world, -32, 37, -475
[Mo., 10. Jan. 2022 18:39:29 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:29 INFO] Couldn't load the location oneblock_world, 415, -62, 295
[Mo., 10. Jan. 2022 18:39:29 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:29 INFO] Couldn't load the location oneblock_world, 415, -62, 275
[Mo., 10. Jan. 2022 18:39:29 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:29 INFO] Couldn't load the location oneblock_world, 415, -62, 255
[Mo., 10. Jan. 2022 18:39:29 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:29 INFO] Couldn't load the location oneblock_world, 435, -62, 295
[Mo., 10. Jan. 2022 18:39:29 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:29 INFO] Couldn't load the location oneblock_world, 435, -62, 275
[Mo., 10. Jan. 2022 18:39:29 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:29 INFO] Couldn't load the location oneblock_world, 435, -62, 255
[Mo., 10. Jan. 2022 18:39:29 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:29 INFO] Couldn't load the location oneblock_world, 455, -62, 295
[Mo., 10. Jan. 2022 18:39:29 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:29 INFO] Couldn't load the location oneblock_world, 455, -62, 275
[Mo., 10. Jan. 2022 18:39:29 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:29 INFO] Couldn't load the location oneblock_world, 455, -62, 255
[Mo., 10. Jan. 2022 18:39:29 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:29 INFO] Couldn't load the location oneblock_world, 543, 20, 330
[Mo., 10. Jan. 2022 18:39:29 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:29 INFO] Couldn't load the location oneblock_world, 525, 20, 330
[Mo., 10. Jan. 2022 18:39:29 INFO] Index 0 out of bounds for length 0
[18:39]
[Mo., 10. Jan. 2022 18:39:29 INFO] Couldn't load the location oneblock_world, 507, 20, 330
[Mo., 10. Jan. 2022 18:39:31 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:31 INFO] Couldn't load the location oneblock_world, 489, 20, 330
[Mo., 10. Jan. 2022 18:39:31 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:31 INFO] Couldn't load the location oneblock_world, 471, 20, 330
[Mo., 10. Jan. 2022 18:39:31 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:31 INFO] Couldn't load the location oneblock_world, 453, 20, 330
[Mo., 10. Jan. 2022 18:39:31 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:31 INFO] Couldn't load the location oneblock_world, 435, 20, 330
[Mo., 10. Jan. 2022 18:39:31 INFO] Index 0 out of bounds for length 0
[Mo., 10. Jan. 2022 18:39:31 INFO] Couldn't load the location oneblock_world, 417, 20, 330
[Mo., 10. Jan. 2022 18:39:31 INFO] Index 0 out of bounds for length 0`

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it still occurs.
